security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Epika\ClubBundle\Entity\User:
            algorithm: sha512
            iterations: 10
            encode-as-base64: true

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_COMPANY]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain:
            providers: [in_memory,main]
        in_memory:
            users:
                user: { password: userpass, roles: ROLE_USER }
                admin: { password: epika1978, roles: ROLE_SUPER_ADMIN }
        main:
            entity: { class: Epika\ClubBundle\Entity\User, property: username }

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            security: true
            provider: chain
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /
                remember_me: true
            logout:
                path: /logout
                target: /
            remember_me:
                key: %secret%
                lifetime: 3600
                domain: ~
        #dev:
        #    pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/afiliados/perfil, roles: ROLE_USER }
        - { path: ^/afiliados/bonos, roles: ROLE_USER }
        - { path: ^/afiliados, roles: ROLE_SUPER_ADMIN }
        - { path: ^/comercios/activar, roles: ROLE_COMPANY }
        - { path: ^/comercios/validar, roles: ROLE_COMPANY }
        - { path: ^/comercios/perfil, roles: ROLE_COMPANY }
        - { path: ^/comercios/nuevo, roles: ROLE_SUPER_ADMIN }
        - { path: ^/comercios/editar, roles: ROLE_SUPER_ADMIN }
        - { path: ^/comercios, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/bonos/nuevo, roles: ROLE_SUPER_ADMIN }
        - { path: ^/bonos/editar, roles: ROLE_SUPER_ADMIN }
        - { path: ^/bonos/eliminar, roles: ROLE_SUPER_ADMIN }
        - { path: ^/bonos/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/bonos, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/categorias/nueva, roles: ROLE_SUPER_ADMIN }
        - { path: ^/categorias/editar, roles: ROLE_SUPER_ADMIN }
        - { path: ^/categorias/eliminar, roles: ROLE_SUPER_ADMIN }
        - { path: ^/categorias, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/city, roles: ROLE_SUPER_ADMIN }
        - { path: ^/departamentos, roles: ROLE_SUPER_ADMIN }
        - { path: ^/membresias, roles: ROLE_SUPER_ADMIN }
        - { path: ^/usuarios, roles: ROLE_SUPER_ADMIN }
        - { path: ^/contactos, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin/perfil, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }