security:
    encoders:
        Epika\ClubBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:  [ROLE_USER,ROLE_COMPANY]

    providers:
        user_db:
            entity:  { class: EpikaClubBundle:User, property: username }

    firewalls:
        main:
            pattern: ^/
            provider: user_db
            form_login:
                login_path: /login
                check_path: /login_check
                remember_me: true
            logout:
                path: /logout
                target: /index
            remember_me:
                key: myStrongSafePass
                lifetime: 1800
                path: ^/
                domain: ~
            security: true
            anonymous: true
        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/afiliados/micuenta, roles: ROLE_USER }
        #- { path: ^/afiliados, roles: ROLE_ADMIN }
        - { path: ^/comercio/activar, roles: ROLE_COMPANY }
        - { path: ^/comercio, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }

